package de.hamburg.haw.wiii.dao;

// default package
// Generated 30.05.2014 10:56:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Artikel generated by hbm2java
 */
@Entity
@Table(name = "ARTIKEL", schema = "ABC581")
public class Artikel implements java.io.Serializable {

	private short artnr;
	private String artname;
	private Character artgrp;
	private String grpname;
	private Set<Bondaten> bondatens = new HashSet<Bondaten>(0);

	public Artikel() {
	}

	public Artikel(short artnr, String artname) {
		this.artnr = artnr;
		this.artname = artname;
	}

	public Artikel(short artnr, String artname, Character artgrp,
			String grpname, Set<Bondaten> bondatens) {
		this.artnr = artnr;
		this.artname = artname;
		this.artgrp = artgrp;
		this.grpname = grpname;
		this.bondatens = bondatens;
	}

	@Id
	@Column(name = "ARTNR", unique = true, nullable = false, precision = 4, scale = 0)
	public short getArtnr() {
		return this.artnr;
	}

	public void setArtnr(short artnr) {
		this.artnr = artnr;
	}

	@Column(name = "ARTNAME", nullable = false, length = 30)
	public String getArtname() {
		return this.artname;
	}

	public void setArtname(String artname) {
		this.artname = artname;
	}

	@Column(name = "ARTGRP", length = 1)
	public Character getArtgrp() {
		return this.artgrp;
	}

	public void setArtgrp(Character artgrp) {
		this.artgrp = artgrp;
	}

	@Column(name = "GRPNAME", length = 20)
	public String getGrpname() {
		return this.grpname;
	}

	public void setGrpname(String grpname) {
		this.grpname = grpname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "artikel")
	public Set<Bondaten> getBondatens() {
		return this.bondatens;
	}

	public void setBondatens(Set<Bondaten> bondatens) {
		this.bondatens = bondatens;
	}

}
