package de.hamburg.haw.wiii.dao;

// default package
// Generated 30.05.2014 10:56:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Bondaten generated by hbm2java
 */
@Entity
@Table(name = "BONDATEN", schema = "ABC581")
public class Bondaten implements java.io.Serializable {

	private BondatenId id;
	private Datum datum;
	private Kunden kunden;
	private Verkaeufer verkaeufer;
	private Artikel artikel;

	public Bondaten() {
	}

	public Bondaten(BondatenId id) {
		this.id = id;
	}

	public Bondaten(BondatenId id, Datum datum, Kunden kunden,
			Verkaeufer verkaeufer, Artikel artikel) {
		this.id = id;
		this.datum = datum;
		this.kunden = kunden;
		this.verkaeufer = verkaeufer;
		this.artikel = artikel;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "uhrzeit", column = @Column(name = "UHRZEIT", length = 5)),
			@AttributeOverride(name = "artnr", column = @Column(name = "ARTNR", precision = 38, scale = 0)),
			@AttributeOverride(name = "anzahl", column = @Column(name = "ANZAHL", precision = 38, scale = 0)),
			@AttributeOverride(name = "verkaeufer", column = @Column(name = "VERKAEUFER", length = 9)),
			@AttributeOverride(name = "kunde", column = @Column(name = "KUNDE", precision = 38, scale = 0)),
			@AttributeOverride(name = "datum", column = @Column(name = "DATUM", length = 7)),
			@AttributeOverride(name = "preis", column = @Column(name = "PREIS", length = 10)) })
	public BondatenId getId() {
		return this.id;
	}

	public void setId(BondatenId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DATUM", insertable = false, updatable = false)
	public Datum getDatum() {
		return this.datum;
	}

	public void setDatum(Datum datum) {
		this.datum = datum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KUNDE", insertable = false, updatable = false)
	public Kunden getKunden() {
		return this.kunden;
	}

	public void setKunden(Kunden kunden) {
		this.kunden = kunden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VERKAEUFER", insertable = false, updatable = false)
	public Verkaeufer getVerkaeufer() {
		return this.verkaeufer;
	}

	public void setVerkaeufer(Verkaeufer verkaeufer) {
		this.verkaeufer = verkaeufer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ARTNR", insertable = false, updatable = false)
	public Artikel getArtikel() {
		return this.artikel;
	}

	public void setArtikel(Artikel artikel) {
		this.artikel = artikel;
	}

}
