package de.hamburg.haw.wiii.dao;

// default package
// Generated 30.05.2014 10:56:20 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BondatenId generated by hbm2java
 */
@Embeddable
public class BondatenId implements java.io.Serializable {

	private String uhrzeit;
	private BigDecimal artnr;
	private BigDecimal anzahl;
	private String verkaeufer;
	private BigDecimal kunde;
	private Date datum;
	private String preis;

	public BondatenId() {
	}

	public BondatenId(String uhrzeit, BigDecimal artnr, BigDecimal anzahl,
			String verkaeufer, BigDecimal kunde, Date datum, String preis) {
		this.uhrzeit = uhrzeit;
		this.artnr = artnr;
		this.anzahl = anzahl;
		this.verkaeufer = verkaeufer;
		this.kunde = kunde;
		this.datum = datum;
		this.preis = preis;
	}

	@Column(name = "UHRZEIT", length = 5)
	public String getUhrzeit() {
		return this.uhrzeit;
	}

	public void setUhrzeit(String uhrzeit) {
		this.uhrzeit = uhrzeit;
	}

	@Column(name = "ARTNR", precision = 38, scale = 0)
	public BigDecimal getArtnr() {
		return this.artnr;
	}

	public void setArtnr(BigDecimal artnr) {
		this.artnr = artnr;
	}

	@Column(name = "ANZAHL", precision = 38, scale = 0)
	public BigDecimal getAnzahl() {
		return this.anzahl;
	}

	public void setAnzahl(BigDecimal anzahl) {
		this.anzahl = anzahl;
	}

	@Column(name = "VERKAEUFER", length = 9)
	public String getVerkaeufer() {
		return this.verkaeufer;
	}

	public void setVerkaeufer(String verkaeufer) {
		this.verkaeufer = verkaeufer;
	}

	@Column(name = "KUNDE", precision = 38, scale = 0)
	public BigDecimal getKunde() {
		return this.kunde;
	}

	public void setKunde(BigDecimal kunde) {
		this.kunde = kunde;
	}

	@Column(name = "DATUM", length = 7)
	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	@Column(name = "PREIS", length = 10)
	public String getPreis() {
		return this.preis;
	}

	public void setPreis(String preis) {
		this.preis = preis;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BondatenId))
			return false;
		BondatenId castOther = (BondatenId) other;

		return ((this.getUhrzeit() == castOther.getUhrzeit()) || (this
				.getUhrzeit() != null && castOther.getUhrzeit() != null && this
				.getUhrzeit().equals(castOther.getUhrzeit())))
				&& ((this.getArtnr() == castOther.getArtnr()) || (this
						.getArtnr() != null && castOther.getArtnr() != null && this
						.getArtnr().equals(castOther.getArtnr())))
				&& ((this.getAnzahl() == castOther.getAnzahl()) || (this
						.getAnzahl() != null && castOther.getAnzahl() != null && this
						.getAnzahl().equals(castOther.getAnzahl())))
				&& ((this.getVerkaeufer() == castOther.getVerkaeufer()) || (this
						.getVerkaeufer() != null
						&& castOther.getVerkaeufer() != null && this
						.getVerkaeufer().equals(castOther.getVerkaeufer())))
				&& ((this.getKunde() == castOther.getKunde()) || (this
						.getKunde() != null && castOther.getKunde() != null && this
						.getKunde().equals(castOther.getKunde())))
				&& ((this.getDatum() == castOther.getDatum()) || (this
						.getDatum() != null && castOther.getDatum() != null && this
						.getDatum().equals(castOther.getDatum())))
				&& ((this.getPreis() == castOther.getPreis()) || (this
						.getPreis() != null && castOther.getPreis() != null && this
						.getPreis().equals(castOther.getPreis())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUhrzeit() == null ? 0 : this.getUhrzeit().hashCode());
		result = 37 * result
				+ (getArtnr() == null ? 0 : this.getArtnr().hashCode());
		result = 37 * result
				+ (getAnzahl() == null ? 0 : this.getAnzahl().hashCode());
		result = 37
				* result
				+ (getVerkaeufer() == null ? 0 : this.getVerkaeufer()
						.hashCode());
		result = 37 * result
				+ (getKunde() == null ? 0 : this.getKunde().hashCode());
		result = 37 * result
				+ (getDatum() == null ? 0 : this.getDatum().hashCode());
		result = 37 * result
				+ (getPreis() == null ? 0 : this.getPreis().hashCode());
		return result;
	}

}
