package de.hamburg.haw.wiii.dao;

// default package
// Generated 30.05.2014 10:56:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filialen generated by hbm2java
 */
@Entity
@Table(name = "FILIALEN", schema = "ABC581")
public class Filialen implements java.io.Serializable {

	private String id;
	private String name;
	private String ort;
	private Set<Verkaeufer> verkaeufers = new HashSet<Verkaeufer>(0);

	public Filialen() {
	}

	public Filialen(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public Filialen(String id, String name, String ort,
			Set<Verkaeufer> verkaeufers) {
		this.id = id;
		this.name = name;
		this.ort = ort;
		this.verkaeufers = verkaeufers;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 1)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ORT", length = 10)
	public String getOrt() {
		return this.ort;
	}

	public void setOrt(String ort) {
		this.ort = ort;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filialen")
	public Set<Verkaeufer> getVerkaeufers() {
		return this.verkaeufers;
	}

	public void setVerkaeufers(Set<Verkaeufer> verkaeufers) {
		this.verkaeufers = verkaeufers;
	}

}
