package de.hamburg.haw.wiii.dao;

// default package
// Generated 30.05.2014 10:56:20 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kunden generated by hbm2java
 */
@Entity
@Table(name = "KUNDEN", schema = "ABC581")
public class Kunden implements java.io.Serializable {

	private BigDecimal id;
	private String vorname;
	private String nachname;
	private String strasse;
	private String plz;
	private String stadt;
	private Set<Bondaten> bondatens = new HashSet<Bondaten>(0);

	public Kunden() {
	}

	public Kunden(BigDecimal id, String vorname, String nachname,
			String strasse, String plz, String stadt) {
		this.id = id;
		this.vorname = vorname;
		this.nachname = nachname;
		this.strasse = strasse;
		this.plz = plz;
		this.stadt = stadt;
	}

	public Kunden(BigDecimal id, String vorname, String nachname,
			String strasse, String plz, String stadt, Set<Bondaten> bondatens) {
		this.id = id;
		this.vorname = vorname;
		this.nachname = nachname;
		this.strasse = strasse;
		this.plz = plz;
		this.stadt = stadt;
		this.bondatens = bondatens;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "VORNAME", nullable = false, length = 25)
	public String getVorname() {
		return this.vorname;
	}

	public void setVorname(String vorname) {
		this.vorname = vorname;
	}

	@Column(name = "NACHNAME", nullable = false, length = 40)
	public String getNachname() {
		return this.nachname;
	}

	public void setNachname(String nachname) {
		this.nachname = nachname;
	}

	@Column(name = "STRASSE", nullable = false, length = 50)
	public String getStrasse() {
		return this.strasse;
	}

	public void setStrasse(String strasse) {
		this.strasse = strasse;
	}

	@Column(name = "PLZ", nullable = false, length = 5)
	public String getPlz() {
		return this.plz;
	}

	public void setPlz(String plz) {
		this.plz = plz;
	}

	@Column(name = "STADT", nullable = false, length = 40)
	public String getStadt() {
		return this.stadt;
	}

	public void setStadt(String stadt) {
		this.stadt = stadt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kunden")
	public Set<Bondaten> getBondatens() {
		return this.bondatens;
	}

	public void setBondatens(Set<Bondaten> bondatens) {
		this.bondatens = bondatens;
	}

}
