package de.hamburg.haw.wiii.dao;

// default package
// Generated 30.05.2014 10:56:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Verkaeufer generated by hbm2java
 */
@Entity
@Table(name = "VERKAEUFER", schema = "ABC581")
public class Verkaeufer implements java.io.Serializable {

	private String verkaeufer;
	private Filialen filialen;
	private String geburtstag;
	private String wohnort;
	private Set<Bondaten> bondatens = new HashSet<Bondaten>(0);

	public Verkaeufer() {
	}

	public Verkaeufer(String verkaeufer) {
		this.verkaeufer = verkaeufer;
	}

	public Verkaeufer(String verkaeufer, Filialen filialen, String geburtstag,
			String wohnort, Set<Bondaten> bondatens) {
		this.verkaeufer = verkaeufer;
		this.filialen = filialen;
		this.geburtstag = geburtstag;
		this.wohnort = wohnort;
		this.bondatens = bondatens;
	}

	@Id
	@Column(name = "VERKAEUFER", unique = true, nullable = false, length = 9)
	public String getVerkaeufer() {
		return this.verkaeufer;
	}

	public void setVerkaeufer(String verkaeufer) {
		this.verkaeufer = verkaeufer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FILIALE")
	public Filialen getFilialen() {
		return this.filialen;
	}

	public void setFilialen(Filialen filialen) {
		this.filialen = filialen;
	}

	@Column(name = "GEBURTSTAG", length = 10)
	public String getGeburtstag() {
		return this.geburtstag;
	}

	public void setGeburtstag(String geburtstag) {
		this.geburtstag = geburtstag;
	}

	@Column(name = "WOHNORT", length = 10)
	public String getWohnort() {
		return this.wohnort;
	}

	public void setWohnort(String wohnort) {
		this.wohnort = wohnort;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "verkaeufer")
	public Set<Bondaten> getBondatens() {
		return this.bondatens;
	}

	public void setBondatens(Set<Bondaten> bondatens) {
		this.bondatens = bondatens;
	}

}
